### ISSUE TITLE
Add types for prometheus metrics

### ISSUE THREAD

**Issue by jennyhys** [ledgerwatch/erigon#2599]
Currently, we've configured our node to send prometheus metrics to Datadog. Due to an absence of a TYPE(i.e. `gauge`) for these metrics, these untyped metrics are ignored by default and it requires a manual cast of metrics in the `Datadog config` file to get the metric successfully sent to Datadog. Can the team specify the type for these prometheus metrics in the code? 

```
instances:
  - prometheus_url: http://localhost:26660/debug/metrics/prometheus
    namespace: "erigon"
    type_overrides:
      table_log_branch: gauge
      sync: gauge
```
