### ISSUE TITLE
Support unknown chains

### ISSUE THREAD

**Issue by numonedad** [ledgerwatch/erigon#2931]
# Rationale

Why should this feature exist? Each chain has been specifically added to the source code. Geth gets around this limitation by allowing users to specify their own networkid and bootnode.
What are the use-cases?
I want to use a chain unknown to private or new chains not yet hardcoded into erigon.
# Implementation

Do you have ideas regarding the implementation of this feature?
The cleanest way to provide this type of functionality is to allow ingestion of a config file say ~/erigon.yml or `${XDG_DATA_HOME:-~/.local/share}/erigon/config.yml`.

Proposed format:
```
chains:
  private_network_name:
    networkid: 2001
    bootnodes: 
    - enode://{key}@69.420.69.420:30303
    
```

Are you willing to implement this feature?
Yes, I can work on this feature.
