### ISSUE TITLE
Connection refused from rpcdaemon to erigon for all "remote" methods.

### ISSUE THREAD

**Issue by darklow** [ledgerwatch/erigon#3111]
#### System information
erigon version 2021.10.2-alpha
git_branch=stable git_tag=v2021.10.02 git_commit=8b4d31f6617a051285e62ef065d4a9de2a439fb2
OS & Version: Alpine Linux / Docker / Based on official example file
Network: mainnet

#### Expected behaviour

rpcdaemon can successfully connect to erigon for all neccessary methods. Everything was working just fine (~2 months old version) until we upgraded to recent erigon version to support Arrow Glacier fork. 

#### Actual behaviour

Now after upgrade to recent version all the "remote" methods like `txpool_content` or `eth_sendRawTransaction` fail with same error while erigon shows no errors:
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "txpool_content", "params": [], "id":1}' IP:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9090: connect: connection refused\""}}
```
or same error from rpcdaemon docker logs for `eth_sendRawTransaction`:
```
rpcdaemon  | [WARN] [12-10|11:53:01.056] Served. conn=IP:59362 method=eth_sendRawTransaction reqid=0 t=200.056µs err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9090: connect: connection refused\""
```

Regular methods like `eth_blockNumber` work just fine.

Are there any new steps necessary to make it work, some kind of new permission control, because we are running in remote mode based on original docker-compose setup.

#### Steps to reproduce the behaviour

```yml
services:
  erigon:
    image: thorax/erigon:devel
    container_name: erigon
    restart: unless-stopped
    volumes:
      - erigon:/home/erigon/.local/share/erigon
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "30304:30304/tcp"
      - "30304:30304/udp"
    command: erigon --private.api.addr=0.0.0.0:9090
    networks:
      - project
    ....

  rpcdaemon:
    image: thorax/erigon:devel
    command: rpcdaemon --private.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,net,web3,debug,txpool,trace
    container_name: rpcdaemon
    ports:
      - "8545:8545"
    restart: unless-stopped
    links:
      - erigon
    networks:
      - project
    ....
```
