### ISSUE TITLE
Cannot broadcast new transactions. Error: pool not started yet

### ISSUE THREAD

**Issue by darklow** [ledgerwatch/erigon#3326]
#### System information

git_branch=stable git_tag=v2022.01.02 git_commit=b4b8df998363298dfc4e36c25da60c5142534594
OS & Version: Alpine Linux / Docker / Based on official example file
Network: mainnet

#### Expected behaviour

Tx is successfully broadcast to network using `eth_sendRawTransaction`.

#### Actual behaviour

After upgrade to newest version no transactions are being broadcast and I see following error in logs:

`rpcdaemon  | [WARN] [01-22|18:52:52.921] Served   conn=IP:41546 method=eth_sendRawTransaction reqid=0 t=410.15µs err="rpc error: code = Unknown desc = pool not started yet"`

Also tried newest dev version, tried downgrading to earlier version as early as it is possible, but same error each time. All was working just fine before update.

We did this update on two full nodes and each of them have same bug now.

Previous version was 2021.10.2-alpha.

**Comment by AskAlexSharov** [comment]
show erigon logs
cli flags of erigon and rpcdaemon

**Comment by darklow** [comment]
Even after more than 24h both nodes can't broadcast any tx, so it doesn't seem like an issue related to not being yet synced. Also both nodes are well synced up to latest block and all the read RPC endpoints work fine.

Erigon logs show nothing at all in the moment of calling eth_sendRawTransaction. Only log entry is only for `rpcdaemon`, the same as I posted already.

Here is the cli commands from docker .yml file:
```
erigon:
  command: erigon --private.api.addr=0.0.0.0:9090

rpcdaemon:
  command: rpcdaemon --private.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,net,web3,debug,txpool,trace --txpool.api.addr=erigon:9090
```
