### ISSUE TITLE
2022.99.99-dev-b6440eea - devel failing to sync: err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"

### ISSUE THREAD

**Issue by breezytm** [ledgerwatch/erigon#4727]
#### System information

Erigon version: `./erigon version 2022.99.99-dev-b6440eea`

OS & Version: ``Ubuntu 20.04 LTS``

#### Expected behaviour

Erigon sync normally after downloading the snapshot

#### Actual behaviour

Erigon throws the following error endlessly ``err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"``

#### Steps to reproduce the behavior

docker-compose.yml

```
version: '2.2'

# Basic erigon's service
services:
  erigon:
    image: thorax/erigon:${TAG:-devel}
    user: root
    command: erigon ${ERIGON_FLAGS-} --datadir=/home/erigon/.local/share/erigon --private.api.addr=0.0.0.0:9090 --downloader.api.addr=downloader:9093
    volumes:
      # This is "datadir". It's ok to mount sub-dirs of "datadir" to different drives
      - ./data/erigon:/home/erigon/.local/share/erigon
    ports:
      - "30306:30303/tcp"
      - "30306:30303/udp"
    restart: unless-stopped

  downloader:
    image: thorax/erigon:${TAG:-devel}
    user: root
    command: downloader ${DOWNLOADER_FLAGS-} --downloader.api.addr=0.0.0.0:9093 --torrent.download.rate=100mb  --torrent.download.slots=6
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes_from:
      - erigon
    ports: [ "42069:42069/tcp", "42069:42069/udp" ]

  rpcdaemon: # Service to server JSON-RCP API
    image: thorax/erigon:${TAG:-devel}
    user: root
    command: rpcdaemon --datadir=/home/erigon/.local/share/erigon --private.api.addr=erigon:9090 --txpool.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,debug,net,trace,web3 --ws
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes_from:
      - erigon
    ports:
      - "8585:8545"
    restart: unless-stopped
```
#### Backtrace

````
erigon_1      | [INFO] [07-16|00:46:29.376] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=467.2MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:46:30.268] [Snapshots] Downloading                  progress="98.96% 205.3GB/207.5GB" download=28.8MB/s upload=0B/s peers=15 connections=16 files=87
erigon_1      | [INFO] [07-16|00:46:39.401] [Snapshots] download                     progress="99.30% 206.1GB/207.5GB" download=37.0MB/s upload=0B/s peers=16 connections=16 files=87 alloc=493.2MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:46:50.280] [Snapshots] Downloading                  progress="99.30% 206.1GB/207.5GB" download=37.0MB/s upload=0B/s peers=16 connections=16 files=87
erigon_1      | [INFO] [07-16|00:46:59.403] [Snapshots] download                     progress="99.63% 206.8GB/207.5GB" download=35.1MB/s upload=0B/s peers=14 connections=14 files=87 alloc=530.5MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:47:10.268] [Snapshots] Downloading                  progress="99.63% 206.8GB/207.5GB" download=35.1MB/s upload=0B/s peers=14 connections=14 files=87
erigon_1      | [INFO] [07-16|00:47:19.402] [Snapshots] download                     progress="99.97% 207.4GB/207.5GB" download=35.5MB/s upload=0B/s peers=11 connections=11 files=87 alloc=567.2MB sys=840.2MB
erigon_1      | [INFO] [07-16|00:47:29.339] [p2p] GoodPeers                          eth66=33
erigon_1      | [INFO] [07-16|00:47:29.377] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=404.6MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:47:30.268] [Snapshots] Downloading                  progress="99.97% 207.4GB/207.5GB" download=35.5MB/s upload=0B/s peers=11 connections=11 files=87
downloader_1  | [INFO] [07-16|00:47:50.267] [Snapshots] Seeding                      up=0B/s peers=3 connections=3 files=87
downloader_1  | [INFO] [07-16|00:47:59.407] [snapshots] Verifying                    progress=17.79%
downloader_1  | [INFO] [07-16|00:48:10.268] [Snapshots] Seeding                      up=819.2PB/s peers=1 connections=1 files=87
downloader_1  | [INFO] [07-16|00:48:19.429] [snapshots] Verifying                    progress=34.79%
erigon_1      | [INFO] [07-16|00:48:29.377] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=487.7MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:48:30.268] [Snapshots] Seeding                      up=0B/s peers=2 connections=2 files=87
downloader_1  | [INFO] [07-16|00:48:39.407] [snapshots] Verifying                    progress=51.65%
downloader_1  | [INFO] [07-16|00:48:50.268] [Snapshots] Seeding                      up=0B/s peers=4 connections=4 files=87
downloader_1  | [INFO] [07-16|00:48:59.403] [snapshots] Verifying                    progress=67.77%
downloader_1  | [INFO] [07-16|00:49:10.268] [Snapshots] Seeding                      up=0B/s peers=3 connections=3 files=87
downloader_1  | [INFO] [07-16|00:49:19.403] [snapshots] Verifying                    progress=81.12%
erigon_1      | [INFO] [07-16|00:49:29.339] [p2p] GoodPeers                          eth66=33
erigon_1      | [INFO] [07-16|00:49:29.415] [txpool] stat                            block=0 pending=1 baseFee=0 queued=180 alloc=379.9MB sys=840.2MB
downloader_1  | [INFO] [07-16|00:49:30.267] [Snapshots] Seeding                      up=0B/s peers=4 connections=4 files=87
downloader_1  | [INFO] [07-16|00:49:39.402] [snapshots] Verifying                    progress=92.34%
downloader_1  | [INFO] [07-16|00:49:50.268] [Snapshots] Seeding                      up=0B/s peers=3 connections=3 files=87
downloader_1  | [INFO] [07-16|00:49:59.404] [snapshots] Verifying                    progress=99.90%
erigon_1      | [INFO] [07-16|00:50:00.135] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=433.4MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:00.135] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:00.136] [Snapshots] see new                      blocks=0
erigon_1      | [INFO] [07-16|00:50:00.636] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:00.638] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=434.1MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:00.638] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:00.639] [Snapshots] see new                      blocks=0
erigon_1      | [INFO] [07-16|00:50:01.139] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:01.141] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=435.4MB sys=840.2MB
rpcdaemon_1   | [INFO] [07-16|00:50:01.141] [Snapshots] see new                      blocks=0
erigon_1      | [EROR] [07-16|00:50:01.141] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
erigon_1      | [INFO] [07-16|00:50:01.642] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:01.644] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=436.8MB sys=840.2MB
rpcdaemon_1   | [INFO] [07-16|00:50:01.644] [Snapshots] see new                      blocks=0
erigon_1      | [EROR] [07-16|00:50:01.644] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
erigon_1      | [INFO] [07-16|00:50:02.145] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:02.147] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=438.5MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:02.147] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:02.147] [Snapshots] see new                      blocks=0
erigon_1      | [INFO] [07-16|00:50:02.648] [Snapshots] Fetching torrent files metadata 
erigon_1      | [INFO] [07-16|00:50:02.650] [Snapshots] Stat                         blocks=0 segments=0 indices=0 alloc=439.9MB sys=840.2MB
erigon_1      | [EROR] [07-16|00:50:02.650] Staged Sync                              err="[1/16 Headers] ancestor is nil. height 1, hash d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"
rpcdaemon_1   | [INFO] [07-16|00:50:02.650] [Snapshots] see new                      blocks=0
````
