### ISSUE TITLE
docker-compose.yml: when --datadir is missing

### ISSUE THREAD

**Issue by roderik** [ledgerwatch/erigon#4780]
Without --datadir, the snapshots are written in the docker container, not in the mounted volume

https://github.com/ledgerwatch/erigon/blob/42e59618a7e933c617e3cb50821e7ed5c454534f/docker-compose.yml#L50

**Comment by AskAlexSharov** [comment]
It imports all volumes from erigon: https://github.com/ledgerwatch/erigon/blob/42e59618a7e933c617e3cb50821e7ed5c454534f/docker-compose.yml#L20

**Comment by roderik** [comment]
@AskAlexSharov I would like to reopen this, I rebuilt a node this weekend and experienced quite some issues with the included docker compose file:

- downloader, volume is mounted, but snapshots are not put in that volume. Our setup is based roughly on https://github.com/allada/bsc-archive-snapshot/blob/master/build_archive_node.sh without using their snapshots but with the 50gb docker volume. The snapshots are stored in the container fs and not the volume (not sure exactly where) until it crashed ugly when the 50gb is full. Adding the datadir to the default path fixes this.
- snapshots then download nicely, but after getting them it halts with no messages. Trying to run reindex manually showed me the db folder had the wrong permissions (created by downloader in a folder where it can download snapshots, so it does not apply the right permissions on create)
- after this, it does the verify step, and halts again. No message, no way to kick it into doing anything except starting to download headers from the network at height 0. I moved back to a single erigon container and then it starts pulling in the data from the snapshots at an incredibly fast pace (so what I was expecting to happen with snapshots)

So, it all works, but also not really without a ton of debugging and doing a custom docker compose file.

**Comment by AskAlexSharov** [comment]
1. downloader has same default datadir as erigon: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html and it imports all volumes from erigon in docker-compose.yml - anything wrong with this logic?
2. permissions - is in-general complex topic in Docker - maybe somebody can simplify it. You can try to follow: https://github.com/ledgerwatch/erigon#run-all-components-by-docker-compose (there are several `make` targets to help with users). 
3. "halts again" - we have several issues about it, some are fixed, some are not. maybe you saw the same issue. 
4. "doing a custom docker compose file" - docker-compose.yml file says `This file is an example: how to start Erigon's services as separated processes`. If your case is simple - just run all-in-one erigon. If your case is complex - then only you know requirements of your project - provide "cloud-native-enterprise-scale-zero-downtime-deploy" is out of erigon's project scope. Anyway we are happy to improve/simplify our docker-compose.yml :-)
5.

**Comment by AskAlexSharov** [comment]
I just disabled build-in Ergion's downloader - maybe they did conflict with external: 
https://github.com/ledgerwatch/erigon/pull/5135

**Comment by roderik** [comment]
I think I know what is happening

When you look at https://hub.docker.com/layers/erigon/thorax/erigon/v2022.08.02/images/sha256-d026933db0f9e73e433cc54eebc9452924ca76e808b5c95dc7416fe6932abfd6?context=explore it runs as user erigon

so the following makes sense
```
  downloader:
    image: thorax/erigon:v2022.08.02
    pid: service:erigon
    volumes:
      - /data/erigon:/home/erigon/.local/share/erigon
    restart: unless-stopped
    mem_swappiness: 0
    command: |
      downloader --torrent.download.rate "120mb" --downloader.api.addr=0.0.0.0:9093
    ports: [ "42069:42069/tcp", "42069:42069/udp" ]
```

My docker runs as root so I need to add the user 

```
  downloader:
    image: thorax/erigon:v2022.08.02
    pid: service:erigon
    volumes:
      - /data/erigon:/home/erigon/.local/share/erigon
    restart: unless-stopped
    mem_swappiness: 0
    command: |
      downloader --torrent.download.rate "120mb" --downloader.api.addr=0.0.0.0:9093
    ports: [ "42069:42069/tcp", "42069:42069/udp" ]
    user: 0:0
```

Now, I'm not 100% on why changing the user the containers runs as, impacts the user inside the container, might happen if the user id exists.

But you see that it in the path it echo's
```
mainnet-downloader-1  | [INFO] [08-21|06:22:35.859] Run snapshot downloader                  addr=0.0.0.0:9093 datadir=/root/.local/share/erigon download.rate=120MB upload.rate=4MB
```

But the volume is /home/erigon..., this is why adding the datadir works

So, putting `user:` to something else than the default 1000 and not doing the "[build](https://github.com/ledgerwatch/erigon/blob/devel/docker-compose.yml#L28-L32)" step for all containers, not only erigon main, makes [this comment in the compose file](https://github.com/ledgerwatch/erigon/blob/devel/docker-compose.yml#L6), wrong as it is actually is ~/ and not /home/erigon

So in my first post, the build steps in the other containers would be missing, and in the current setup, the user ends up the existing "root" user and the volume mappings are wrong.

I assume some of the halting issues are due to not putting the datadir on all containers
