### ISSUE TITLE
~850G Disk usage and still unsynced?

### ISSUE THREAD

**Issue by RisingPaw** [ledgerwatch/erigon#5282]
Don't think it's a bug, maybe just wrong configuration but I've been syncing Erigon for around 3 days, and the disk usage seems very high `841G`, while my synced geth is at `611G`. Is it expected? Can it be reduced by pruning?

Sidenote, the discord invite link (in this issue template for a q) is invalid. 

Using `thorax/erigon:`
`sha256:c3fc1345cc34f462660edb3b76d4b05b8290b113b4ade0ce565ee8b0017afbb3`

```
9.9M	./volumes/erigon/snapshots/db
241G	./volumes/erigon/snapshots
2.8M	./volumes/erigon/nodes/eth66
4.0K	./volumes/erigon/nodes
600G	./volumes/erigon/chaindata
4.0K	./volumes/erigon/agg22
16K	./volumes/erigon/etl-temp
20M	./volumes/erigon/txpool
```

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "currentBlock": "0x0",
    "highestBlock": "0xebdc0f",
    "stages": [
      {
        "stage_name": "Headers",
        "block_number": "0xebdc0f"
      },
      {
        "stage_name": "BlockHashes",
        "block_number": "0xebdc0f"
      },
      {
        "stage_name": "Bodies",
        "block_number": "0xebdc0f"
      },
      {
        "stage_name": "Senders",
        "block_number": "0xebdc0f"
      },
      {
        "stage_name": "Execution",
        "block_number": "0xae184e"
      },
      {
        "stage_name": "Translation",
        "block_number": "0x0"
      },
      {
        "stage_name": "HashState",
        "block_number": "0x0"
      },
      {
        "stage_name": "IntermediateHashes",
        "block_number": "0x0"
      },
      {
        "stage_name": "AccountHistoryIndex",
        "block_number": "0x0"
      },
      {
        "stage_name": "StorageHistoryIndex",
        "block_number": "0x0"
      },
      {
        "stage_name": "LogIndex",
        "block_number": "0x0"
      },
      {
        "stage_name": "CallTraces",
        "block_number": "0x0"
      },
      {
        "stage_name": "TxLookup",
        "block_number": "0x0"
      },
      {
        "stage_name": "Finish",
        "block_number": "0x0"
      }
    ]
  }
}
```

My docker-compose file:

```yml
# https://hub.docker.com/r/thorax/erigon/tags

version: "2.3"

services:
  erigon:
    image: thorax/erigon:${TAG:-alpha}
    restart: unless-stopped
    stop_grace_period: 60s
    mem_swappiness: 0
    container_name: erigon
    hostname: erigon
    ports:
      - "${HOST_IP:-0.0.0.0}:${PORT:-30303}:${PORT:-30303}"
      - "${HOST_IP:-0.0.0.0}:${TORRENT_PORT:-42069}:${TORRENT_PORT:-42069}"
      - "${LOCAL_IP:-127.0.0.1}:8545:8545"
      - "${LOCAL_IP:-127.0.0.1}:8546:8546"
      - "${LOCAL_IP:-127.0.0.1}:8551:8551"
    expose:
      - 8545
      - 8546
      - 8551
      - 6060
      - 6061
      - 9090
    volumes:
      - "./volumes/erigon:/home/erigon/.local/share/erigon:rw"
    entrypoint: /usr/local/bin/erigon
    command:
      - --datadir=/home/erigon/.local/share/erigon
      - --port=${PORT:-30303}
      - --chain=${NETWORK:-mainnet}
      - --private.api.addr=0.0.0.0:9090
      - --torrent.download.rate=32mb
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=web3,eth,net,engine
      - --ws
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --maxpeers=50
    mem_limit: 16G
```
