### ISSUE TITLE
The method `erigon_BlockNumber` does not exist/is not available

### ISSUE THREAD

**Issue by Texnomic** [ledgerwatch/erigon#5986]
#### System information

Erigon version: 2.29.0

OS & Version: Ubuntu Server

#### Actual behaviour
```json
{
  "id": "f84201da-8e68-4174-8645-788f5f70ec15",
  "jsonrpc": "2.0",
  "method": "erigon_BlockNumber",
  "params": [
    "finalized"
  ]
}
```
```json
{
  "jsonrpc": "2.0",
  "id": "f84201da-8e68-4174-8645-788f5f70ec15",
  "error": {
    "code": -32601,
    "message": "the method erigon_BlockNumber does not exist/is not available"
  }
}
```

### YAML Config 

````yaml
# -----------------
# Basics
# -----------------
chain: "mainnet"
datadir: "/mnt/data"
history.v2: "false"
watch-the-burn: "true"
snapshots: "true"
healthcheck: "true"

# -----------------
# P2P
# -----------------
nat: "extip:<SNIP>"
port: "<SNIP>"
maxpeers: "200"
v5disc: "true"

# -----------------
# Json-RPC Over HTTP
# -----------------
http: "true"
http.trace: "false"
http.compression: "false"
http.addr: "0.0.0.0"
http.port: "8545"
http.api: "eth,erigon,engine,web3,net,debug,trace,txpool,db,parity"
http.vhosts: "*"
http.corsdomain: "*"

# -----------------
# Json-RPC Over WebSocket
# -----------------
ws: "true"
ws.compression: "false"

# -----------------
# Engine API
# -----------------
authrpc.addr: "0.0.0.0"
authrpc.port: "8551"
authrpc.vhosts: "*"

# -----------------
# Private API
# -----------------
private.api.addr: "0.0.0.0:9090"

# -----------------
# Memory Pool
# -----------------
txpool.globalslots: "1000000"
txpool.globalbasefeeslots: "1000000"
txpool.globalqueue: "1000000"
txpool.lifetime: "720h"

# -----------------
# Downloader
# -----------------
torrent.maxpeers: "1"
torrent.upload.rate: "1kb"
torrent.download.rate: "1mb"
no-downloader: "false"

# -----------------
# Metrics
# -----------------
metrics.addr: "0.0.0.0"
metrics.port: "6070"
metrics: "true"
metrics.expensive: "true"

# -----------------
# pprof
# -----------------
pprof.addr: "0.0.0.0"
pprof.port: "6060"
pprof: "true"
````
