### ISSUE TITLE
BSC: slow sync 

### ISSUE THREAD

**Issue by BNB666666666** [ledgerwatch/erigon#6022]
#### System information
CPU：Xeon E5 2680 x2 (16cores)

RAM:64G
Disk:SSD 2T
Erigon version: `./erigon --version`
2.28.0
OS & Version: Windows/Linux/OSX
OS:CENTOS 7.9
Commit hash : 

#### Expected behaviour
sync faster

#### Actual behaviour
![image](https://user-images.githubusercontent.com/117515691/201124436-61ad2fee-73f0-4bc2-8752-b9f95df923da.png)
![image](https://user-images.githubusercontent.com/117515691/201123652-f53b6a14-193e-409a-82cb-b5dccb4d58ca.png)

#### Steps to reproduce the behaviour
./erigon --chain=bsc --prune=hrtc --db.pagesize=16k --datadir /run/media/xxx/erigondata/erigon --private.api.addr=0.0.0.0:9090 -metrics --metrics.addr=0.0.0.0 --metrics.port=9350 --pprof --pprof.addr=0.0.0.0 --pprof.port=9351 --torrent.download.rate=20mb

#### Backtrace
I just downloaded 'erigon.22575695.tar.lz4' from BNB48CLUB then compressed it , when I run the erigon ,it sync super slowly

**Comment by BNB666666666** [comment]
networksyncing : BSC

**Comment by AskAlexSharov** [comment]
You can try warmup after reboot by:
make db-tools
./build/bin/mdbx_dump -s PlainState /chaindata > /dev/null
 
Write
Preview

**Comment by naviocean** [comment]
I got the same issue.
```
erigon_1      | [INFO] [11-12|16:08:04.971] [7/16 Execution] Executed blocks         number=22978706 blk/s=2.1 tx/s=234.1 Mgas/s=30.1 gasState=0.15 batch=192.5MB alloc=3.1GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:08:23.074] [7/16 Execution] Executed blocks         number=22978728 blk/s=1.2 tx/s=180.5 Mgas/s=21.8 gasState=0.15 batch=193.4MB alloc=3.3GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:08:43.412] [7/16 Execution] Executed blocks         number=22978764 blk/s=1.8 tx/s=212.0 Mgas/s=25.4 gasState=0.15 batch=194.6MB alloc=3.5GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:09:03.094] [7/16 Execution] Executed blocks         number=22978795 blk/s=1.6 tx/s=176.7 Mgas/s=25.3 gasState=0.15 batch=195.9MB alloc=3.7GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:09:23.249] [7/16 Execution] Executed blocks         number=22978847 blk/s=2.6 tx/s=280.3 Mgas/s=34.6 gasState=0.15 batch=197.5MB alloc=4.0GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:09:43.442] [7/16 Execution] Executed blocks         number=22978896 blk/s=2.4 tx/s=265.1 Mgas/s=33.1 gasState=0.15 batch=199.0MB alloc=4.3GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:10:03.030] [7/16 Execution] Executed blocks         number=22978949 blk/s=2.7 tx/s=277.3 Mgas/s=32.5 gasState=0.15 batch=200.6MB alloc=3.1GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:10:04.196] [p2p] GoodPeers                          eth66=91
erigon_1      | [INFO] [11-12|16:10:23.159] [7/16 Execution] Executed blocks         number=22979002 blk/s=2.6 tx/s=264.7 Mgas/s=32.4 gasState=0.15 batch=202.3MB alloc=3.4GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:10:43.320] [7/16 Execution] Executed blocks         number=22979040 blk/s=1.9 tx/s=226.1 Mgas/s=28.0 gasState=0.15 batch=203.6MB alloc=3.8GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:11:02.982] [7/16 Execution] Executed blocks         number=22979069 blk/s=1.5 tx/s=181.8 Mgas/s=23.9 gasState=0.15 batch=204.8MB alloc=4.0GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:11:23.067] [7/16 Execution] Executed blocks         number=22979108 blk/s=1.9 tx/s=197.1 Mgas/s=28.2 gasState=0.16 batch=206.2MB alloc=4.2GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:11:44.505] [7/16 Execution] Executed blocks         number=22979147 blk/s=1.8 tx/s=181.0 Mgas/s=27.1 gasState=0.16 batch=207.7MB alloc=4.5GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:12:04.196] [p2p] GoodPeers                          eth66=91
erigon_1      | [INFO] [11-12|16:12:05.067] [7/16 Execution] Executed blocks         number=22979189 blk/s=2.0 tx/s=214.0 Mgas/s=29.2 gasState=0.16 batch=209.2MB alloc=3.3GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:12:23.257] [7/16 Execution] Executed blocks         number=22979226 blk/s=2.0 tx/s=257.4 Mgas/s=31.6 gasState=0.16 batch=210.5MB alloc=3.5GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:12:46.150] [7/16 Execution] Executed blocks         number=22979273 blk/s=2.1 tx/s=248.1 Mgas/s=33.1 gasState=0.16 batch=212.3MB alloc=3.8GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:13:03.174] [7/16 Execution] Executed blocks         number=22979312 blk/s=2.3 tx/s=268.0 Mgas/s=34.5 gasState=0.16 batch=213.7MB alloc=4.0GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:13:23.197] [7/16 Execution] Executed blocks         number=22979355 blk/s=2.1 tx/s=308.4 Mgas/s=37.8 gasState=0.16 batch=215.2MB alloc=4.4GB sys=8.1GB
erigon_1      | [INFO] [11-12|16:13:43.064] [7/16 Execution] Executed blocks         number=22979395 blk/s=2.0 tx/s=228.8 Mgas/s=31.5 gasState=0.16 batch=216.8MB alloc=4.6GB sys=8.1GB
```

**Comment by AskAlexSharov** [comment]
@naviocean we don't know anything about your setup.

**Comment by BNB666666666** [comment]
> 您可以通过以下方式尝试重新启动后预热： 制作数据库工具 ./build/bin/mdbx_dump -s PlainState /chaindata > /dev/null

thx for response.I use the erigon 2.28.0 client but not the source code.Shall I fix the problem with add the flag: `-s PlainState'?

**Comment by naviocean** [comment]
@AskAlexSharov I use 8TB SSD 7500 IOPS, 64gb Ram, and 32 Cpu cores.
I run Erigon by docker-compose
```
version: '3.9'

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "2m"
      max-file: "10"

services:
  erigon:
    image: thorax/erigon:v2.30.0
    command: |
      erigon --chain bsc
      --snapshots=true
      --db.pagesize=16k
      --datadir=/home/erigon/.local/share/erigon
      --torrent.port=42069 --torrent.upload.rate=15mb --torrent.download.rate=1024mb
      --txpool.disable
    volumes:
      - /erigon/data/mainnet:/home/erigon/.local/share/erigon
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 30304:30304/tcp
      - 30304:30304/udp
      - 8551:8551
    restart: unless-stopped
    mem_swappiness: 0
    <<: *logging
```
