### ISSUE TITLE
Polygon [2/16 Headers] No block headers to write in this log period block number=XXXXXX

### ISSUE THREAD

**Issue by DicksonWu654** [ledgerwatch/erigon#6314]
#### System information

Erigon version: erigon version 2.32.0-dev-94d12a5d

OS & Version: Linux

Commit hash : 94d12a5d3cd63f159e119f7ef91d8ec085ce0e1f

#### Expected behaviour

Syncing normally to the latest block

#### Actual behaviour

Gets stuck on "[2/16 Headers] No block headers to write in this log period block number=XXXXXX" and then spams out "Retrying again in 5 seconds for next Heimdall span path=bor/span/0"

#### Steps to reproduce the behaviour

./build/bin/erigon --datadir=bsc_datadir --chain=bsc --port=30300 --http.port=8544 --authrpc.port=8550 --torrent.port=42068 --private.api.addr=127.0.0.1:9089 --http --ws --http.api=eth,debug,net,trace,web3,erigon --torrent.download.rate=5000mb --externalcl

This bug also occurred on the BSC node, but was fixed recently: https://github.com/ledgerwatch/erigon/issues/5703 & https://github.com/ledgerwatch/erigon/issues/6235

**Comment by 0xKrishna** [comment]
Your heimdall is not working

**Comment by Aracki** [comment]
Having the same issue, even though I checked heimdall and it's executing latest blocks...

**Comment by 0xKrishna** [comment]
This `Retrying again in 5 seconds for next Heimdall span path=bor/span/0` means your heimdall rest-server is not responding.

**Comment by johand-garcia** [comment]
What about `Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list` message? Does it also mean heimdall rest-server is not responding?

The [Detailed changelog](https://github.com/maticnetwork/heimdall/releases/tag/v0.3.0#:~:text=In%20v0.2.x%2C%20heimdalld%2C%20bridge%2C%20and%20rest%2Dserver%20are%20run%20in%20three%20different%20processes.%20In%20v0.3.0%2C%20they%20could%20be%20launched%20together%20in%20a%20single%20process%20with%20one%20CLI%20command.) of heimdall version v0.3.0 says:
`In v0.2.x, heimdalld, bridge, and rest-server are run in three different processes. In v0.3.0, they could be launched together in a single process with one CLI command.`
I started it like this:
```
  heimdall:
    container_name: heimdall
    image: 0xpolygon/heimdall:0.3.0
    command:
      - start
      - rest-server
      - --chain-id=137
      - --home=/home/heimdall/.local/share/heimdall/
      - --p2p.laddr=tcp://0.0.0.0:26656
      - --rpc.laddr=tcp://0.0.0.0:26657         
      - --laddr=tcp://0.0.0.0:1317
    volumes:
      - /data/heimdall:/home/heimdall/.local/share/heimdall
    ports:
      - 26656:26656 # P2P (TCP)
      - 26657:26657 # RPC (TCP)
      - 1317:1317   # Heimdall REST API
 ```
 
 But when it starts step [7/16 Execution] it starts to show up this message:
  ```
 erigon  | [INFO] [12-23|18:44:35.593] [p2p] GoodPeers                          eth66=73 eth67=6
erigon  | [INFO] [12-23|18:44:37.716] [txpool] stat                            block=36789495 pending=10000 baseFee=30000 queued=30000 alloc=6.0GB sys=7.7GB
erigon  | [INFO] [12-23|18:45:14.378] [6/16 Senders] DONE                      in=5m35.245878972s
erigon  | [INFO] [12-23|18:45:14.379] [7/16 Execution] Blocks execution        from=36789495 to=37178432
erigon  | [INFO] [12-23|18:45:22.806] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:45:27.809] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:45:32.809] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:45:37.707] [txpool] stat                            block=36789495 pending=10000 baseFee=30000 queued=30000 alloc=6.7GB sys=7.7GB
erigon  | [INFO] [12-23|18:45:37.810] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:45:42.811] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:45:47.812] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:45:52.812] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:45:57.814] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:46:02.815] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
erigon  | [INFO] [12-23|18:46:07.815] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
 ```
