### ISSUE TITLE
Execution client got stuck

### ISSUE THREAD

**Issue by dzmitrykliapkou** [ledgerwatch/erigon#6751]
#### System information

Erigon version: thorax/erigon:v2.36.1 and thorax/erigon:v2.37.0

OS & Version: Amazon Linux 2

Docker-compose:
```yaml
version: '2.2'

services:
  erigon:
    image: thorax/erigon:v2.37.0
    container_name: erigon
    command:
      - erigon
      - --datadir=/home/erigon/.local/share/erigon
      - --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex
      - --externalcl
      - --private.api.addr=0.0.0.0:9090
      - --http
      - --snapshots=false
      - --http.api=eth,erigon,engine,net
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --ws
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --maxpeers=10
      - --log.json
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 6060:6060
    volumes:
      - "/execution_data:/home/erigon/.local/share/erigon"
    restart: unless-stopped
    mem_swappiness: 0
    stop_signal: SIGINT
    stop_grace_period: 2m
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  lighthouse:
    image: sigp/lighthouse:v3.4.0
    container_name: lighthouse
    depends_on:
      - erigon
    restart: unless-stopped
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "3500:5052"
      - "5054:5054"
    volumes:
      - "/consensus_data/beacon-node:/root/.lighthouse/mainnet"
      - "/execution_data:/tmp/execution_data:ro"
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - lighthouse
      - --network=mainnet
      - beacon
      - --reconstruct-historic-states
      - --http
      - --http-port=5052
      - --http-address=0.0.0.0
      - --execution-endpoint=http://erigon:8551
      - --execution-jwt=/tmp/execution_data/jwt.hex
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=5054
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```

Chain/Network: Ethereum mainnet

#### Expected behaviour
Execution client latest block number grows smoothly

#### Actual behaviour
Erigon got stuck ~12hrs ago at `"block":16521673`. Consensus client continue importing new blocks. I tried to update Erigon to v2.37.0. After that it managed to import ~4k blocks in batch but then got stuck again. Also I still see the repeating line in logs:

```
{"alloc":"3.3GB","baseFee":24038,"block":16521673,"lvl":"info","msg":"[txpool] stat","pending":521,"queued":29295,"sys":"5.8GB","t":"2023-01-31T07:36:48.502639022Z"}
```

#### Steps to reproduce the behaviour
See docker-compose.yaml

#### Logs after update to v2.37.0

[erigon.log](https://github.com/ledgerwatch/erigon/files/10543948/erigon.log)

It is very similar to the issue here: https://github.com/ledgerwatch/erigon/issues/6629
What is the reason of such behavior and how we can avoid this? Because now it prevents us from using Erigon as production-ready client
