### ISSUE TITLE
I cannot accept RPC requests from the outside.

### ISSUE THREAD

**Issue by taiki94** [ledgerwatch/erigon#7295]
Hi I have one question.

I would like to build an erigon node and allow rpc requests to come through from the outside, how do I set this up?

I have been running "v2.38.1" and it worked fine, but with the new version "v2.42.0", I get a ConnectionError when accessing from the outside and access fails.

Here is an excerpt from the docker-compose configuration file that starts erigon.

```
  erigon:
    container_name: erigon
    image: thorax/erigon:${ERIGON_VERSION:-v2.42.0}
    restart: unless-stopped
    volumes:
      - /data:/data
    ports:
      - "8545:8545" # RPC API (TCP)
      - "8551:8551" # Engine API (TCP)
      - "30303:30303" # P2P (TCP)
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "5"
    command:
      - "--datadir=/data/erigon" 
      # - "--datadir=/home/erigon/.local/share/erigon" 
      - "--metrics" 
      - "--metrics.addr=0.0.0.0"
      - "--metrics.port=6060" 
      - "--private.api.addr=0.0.0.0:9090" 
      - "--pprof"
      - "--pprof.addr=0.0.0.0" 
      - "--pprof.port=6061"
      - "--http"
      - "--http.addr=0.0.0.0" 
      - "--http.vhosts=*" 
      - "--http.corsdomain=*" 
      - "--http.api=eth,debug,net,trace,erigon,engine"
      - "--ws"
      - "--rpc.batch.concurrency=20000"
      - "--rpc.batch.limit=50000"
      - "--db.read.concurrency=50000"
      - "--authrpc.jwtsecret=/data/jwt.hex"
      - "--authrpc.addr=0.0.0.0"
      - "--authrpc.vhosts=*"
    expose:
      - 8545
```

I don't know if this is related, but in "v2.38.1" and "v2.42.0", the log when the RPC server starts was changed as follows.
(The URL has changed from "0.0.0.0.0" to "[::]")
```
# v2.38.1
[INFO] [04-09|03:24:55.030] HTTP endpoint opened for Engine API      url=0.0.0.0:8551 ws=true ws.compression=true
[INFO] [04-09|03:24:55.030] HTTP endpoint opened                     url=0.0.0.0:8545 ws=true ws.compression=true grpc=false
```

```
# v2.42.0
[INFO] [04-12|07:05:19.680] HTTP endpoint opened for Engine API      url=[::]:8551 ws=true ws.compression=true
[INFO] [04-12|07:05:19.681] HTTP endpoint opened                     url=[::]:8545 ws=true ws.compression=true grpc=false
```
