### ISSUE TITLE
Consensus Spec tests for Forkchoice.

### ISSUE THREAD

**Issue by Giulio2002** [ledgerwatch/erigon#7394]
# Rationale

Right now there are no consensus tests being ran for Caplin forkchoice. so we need them.

# Implementation

So implementation of the conensus-spec-tests code is at cmd/ef-tests-cl, there you can find the run code. So each test is divided in YAML files and we need to execute the order in which the yaml instruction come. For example:

````
- checks:
    head: {slot: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
- {tick: 12}
- checks:
    time: 12
    head: {slot: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    justified_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    finalized_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    proposer_boost_root: '0x0000000000000000000000000000000000000000000000000000000000000000'
- {block: block_0xc72c3eee9c32f184be5b703bdd9b9932d5d8a104d1153eb2420bc8a9c73375a9}
- checks:
    time: 12
    head: {slot: 1, root: '0x52e0ef631d09872e3cc1011c53aef6749277664d541fc22b556610e4c1bfd2e0'}
    justified_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    finalized_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    proposer_boost_root: '0x52e0ef631d09872e3cc1011c53aef6749277664d541fc22b556610e4c1bfd2e0'
- {tick: 24}
- checks:
    time: 24
    head: {slot: 1, root: '0x52e0ef631d09872e3cc1011c53aef6749277664d541fc22b556610e4c1bfd2e0'}
    justified_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    finalized_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    proposer_boost_root: '0x0000000000000000000000000000000000000000000000000000000000000000'
- {block: block_0x3dc785563392956715b2947aeab815cbef0486624ccbce8021955bad4a08a65d}
- checks:
    time: 24
    head: {slot: 2, root: '0x770d058877053214862779fc86dfa100306ff0c4e4842f1d9089da016b1d57a7'}
    justified_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    finalized_checkpoint: {epoch: 0, root: '0xde0946ce3fd98b8322335d33d9e66210043121806d6158dbdc61d1f349669ba4'}
    proposer_boost_root: '0x770d058877053214862779fc86dfa100306ff0c4e4842f1d9089da016b1d57a7'
- checks:
    head: {slot: 2, root: '0x770d058877053214862779fc86dfa100306ff0c4e4842f1d9089da016b1d57a7'}
````

when there is a check we want to check that the values match. when there is tick we need to call onTick, when there is block we need call onBlock, and so on for onAttestation and onAttesterSlashing. You can see the reference implementation at: https://github.com/ledgerwatch/erigon/blob/82971007bb69a421b62a49aa0fdafdc55cbd8b3f/cmd/erigon-cl/forkchoice/on_attestation.go#L11 . consensus specs for the forkchoice algo is at https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/fork-choice.md .
