### ISSUE TITLE
Upgrade Question (--prune*)

### ISSUE THREAD

**Issue by 0x1un** [ledgerwatch/erigon#7402]
Old Version: v2.37.0
Upgraded Version: v2.43.0

Startup config:
```text
      erigon  --http --http.api=eth,debug,net,trace,web3,erigon --prune=hrtc
      --prune.h.older=15000000 --prune.r.older=0  --prune.t.older=0 --prune.c.older=15000000
      --internalcl=true
      --private.api.addr=0.0.0.0:9090
      --sentry.api.addr=sentry:9091 --downloader.api.addr=downloader:9093 --txpool.disable
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex
      --authrpc.addr=0.0.0.0  --authrpc.vhosts='*' --authrpc.port=8551
      --datadir=/home/erigon/.local/share/erigon
```

Fatal log:
```text
erigon_1      | [INFO] [04-28|13:57:36.988] logging to file system                   log dir=/home/erigon/.local/share/erigon/logs file prefix=erigon log level=info json=false
erigon_1      | [INFO] [04-28|13:57:37.000] Build info                               git_branch=heads/v2.43.0 git_tag=v2.43.0-dirty git_commit=1106475e345d936aa1220ace3e95d746ec361fa4
erigon_1      | [INFO] [04-28|13:57:37.000] Starting Erigon on Ethereum mainnet... 
erigon_1      | [INFO] [04-28|13:57:37.002] Maximum peer count                       ETH=100 total=100
erigon_1      | [INFO] [04-28|13:57:37.002] starting HTTP APIs                       APIs=eth,erigon,engine
erigon_1      | [INFO] [04-28|13:57:37.002] torrent verbosity                        level=WRN
erigon_1      | [INFO] [04-28|13:57:39.108] Set global gas cap                       cap=50000000
erigon_1      | [INFO] [04-28|13:57:39.192] [Downloader] Runnning with               ipv6-enabled=true ipv4-enabled=true download.rate=16mb upload.rate=4mb
erigon_1      | [INFO] [04-28|13:57:39.192] Opening Database                         label=chaindata path=/home/erigon/.local/share/erigon/chaindata
erigon_1      | [INFO] [04-28|13:57:39.192] [db] params: growStep=2GB, mapsSize=7TB, shrinkThreshold=-1, pageSize=4KB, label=chaindata, WriteMap=false, Durable=false, NoReadahead=true,  
erigon_1      | [INFO] [04-28|13:57:39.197] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Shanghai: 1681338455, Cancun: <nil>, Prague: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
erigon_1      | [EROR] [04-28|13:57:39.197] Erigon startup                           err="not allowed change of --prune flag, last time you used: --prune.t.older=90000 --prune.h.older=15000000 --prune.r.before=11052984 --prune.c.older=15000000"
erigon_1      | not allowed change of --prune flag, last time you used: --prune.t.older=90000 --prune.h.older=15000000 --prune.r.before=11052984 --prune.c.older=15000000
```

When I set it to:
```text
--prune.t.older=90000 --prune.h.older=15000000 --prune.r.before=11052984 --prune.c.older=15000000
```
I still report this error.

but when I go back to v2.37.0 and restore old config, It worked fine.
Why?

**Comment by AskAlexSharov** [comment]
hi.
1. " still report this error." - show the error pls.
2. what was your --prune flags in the past?
3. "restore old config" - show prune-related part of this config.

**Comment by 0x1un** [comment]
> hi.
> 
> 1. " still report this error." - show the error pls.
> 2. what was your --prune flags in the past?
> 3. "restore old config" - show prune-related part of this config.

You should review my issue, the description is already very clear.
The following is just a copy of the problem once:

1.  the error:
`erigon_1      | [EROR] [04-28|13:57:39.197] Erigon startup                           err="not allowed change of --prune flag, last time you used: --prune.t.older=90000 --prune.h.older=15000000 --prune.r.before=11052984 --prune.c.older=15000000"`
2. when I set this flag, still report this error.
3. old --prune flags:
`--prune=hrtc --prune.h.older=15000000 --prune.r.older=0  --prune.t.older=0 --prune.c.older=15000000`

**Comment by AskAlexSharov** [comment]
show 
```
make integration
./build/bin/integration print_stages
```
(plz show 2 outputs of old and new "integration" build, tnx)

**Comment by 0x1un** [comment]
Thank you for your reply.

## Version: v2.37.0
It worked fine. But the block sync was stopped, so we decided to upgrade it.
### integration print_stages
```text
--
/ $ integration --chain=mainnet --datadir=/home/erigon/.local/share/erigon print_stages
WARN[05-04|09:20:53.030] no log dir set, console logging only 
INFO[05-04|09:21:03.109] [Snapshots] Blocks Stat                  blocks=16944k indices=16944k alloc=2.2GB sys=2.4GB
Note: prune_at doesn't mean 'all data before were deleted' - it just mean stage.Prune function were run to this block. Because 1 stage may prune multiple data types to different prune distance.

 				 stage_at 	 prune_at
Snapshots 			 17034860 	 0
Headers 			 17034860 	 0
BlockHashes 			 17034860 	 0
Bodies 				 17034860 	 0
Senders 			 17034860 	 0
Execution 			 17034860 	 17034860
Translation 			 0 		 0
HashState 			 17034860 	 0
IntermediateHashes 		 17034860 	 17034860
AccountHistoryIndex 		 17034860 	 17034860
StorageHistoryIndex 		 17034860 	 17034860
LogIndex 			 17034860 	 17034860
CallTraces 			 17034860 	 17034860
TxLookup 			 17034860 	 16944860
Finish 				 17034860 	 0
--
prune distance: --prune.t.older=90000 --prune.h.older=15000000 --prune.r.before=11052984 --prune.c.older=15000000

blocks.v2: blocks=16943999, segments=16943999, indices=16943999

history.v3: false, idx steps: 0.00, lastMaxTxNum=0->0, lastBlockInSnap=0

sequence: EthTx=1967871831, NonCanonicalTx=98310

in db: first header 16944000, last header 17034874, first body 16944000, last body 17034860
--

```
### docker-compose.yaml
```yaml
# Erigon by default is "all in one binary" solution, but it's possible start TxPool as separated processes.
# Same true about: JSON RPC layer (RPCDaemon), p2p layer (Sentry), history download layer (Downloader), consensus.
# Don't start services as separated processes unless you have clear reason for it: resource limiting, scale, replace by your own implementation, security.
# This file is an example: how to start Erigon's services as separated processes.

# Default: --datadir=/home/erigon/.local/share/erigon
# Default UID: 3473
# Default GID: 3473
# Ports: `9090` execution engine (private api), `9091` sentry, `9092` consensus engine, `9093` snapshot downloader, `9094` TxPool
# Ports: `8545` json rpc, `8551` consensus json rpc, `30303` eth p2p protocol, `42069` bittorrent protocol,

# Connections: erigon -> (sentries, downloader), rpcdaemon -> (erigon, txpool), txpool -> erigon

version: '2.2'

networks:
  erigon:
    driver: bridge
    ipam:
     config:
       - subnet: 172.102.1.0/16
         gateway: 172.102.1.1

x-logging: &logging
  logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

# Basic erigon's service
x-erigon-service: &default-erigon-service
  image: thorax/erigon:${TAG:-latest}
  pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
  volumes_from: [ erigon ]
  restart: unless-stopped
  mem_swappiness: 0
  user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
  <<: *logging

services:
  erigon:
    image: thorax/erigon:${TAG:-latest}
    build:
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
      context: .
    environment:
      TZ: "Asia/Shanghai"
    networks:
      erigon:
        ipv4_address: 172.102.1.10
    deploy:
        resources:
          limits:
            cpus: '16'
            memory: '16gb'
          reservations:
            cpus: '16'
            memory: '16gb'
    command: |
      erigon  --http --http.api=eth,debug,net,trace,web3,erigon
      --prune=hrtc
      --prune.h.older=15000000 --prune.r.older=0  --prune.t.older=0 --prune.c.older=15000000
      --externalcl
      --private.api.addr=0.0.0.0:9090 
      --sentry.api.addr=sentry:9091 --downloader.api.addr=downloader:9093 --txpool.disable
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex 
      --authrpc.addr=0.0.0.0  --authrpc.vhosts='*' --authrpc.port=8551
      --datadir=/home/erigon/.local/share/erigon
    ports: ["6061:6060", "6062:6061", "9090:9090"]
    volumes:
      # It's ok to mount sub-dirs of "datadir" to different drives
      - ${XDG_DATA_HOME:-~/.local/share}/erigon:/home/erigon/.local/share/erigon
    restart: unless-stopped
    mem_swappiness: 0
    <<: *logging


  downloader:
    <<: *default-erigon-service
    networks:
      erigon:
        ipv4_address: 172.102.1.12
    command: downloader ${DOWNLOADER_FLAGS-} --downloader.api.addr=0.0.0.0:9093 --datadir=/home/erigon/.local/share/erigon
    ports: [ "5170:42069/tcp", "5170:42069/udp" ]
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"

  sentry:
    <<: *default-erigon-service
    networks:
      erigon:
        ipv4_address: 172.102.1.11
    command: sentry ${SENTRY_FLAGS-} --sentry.api.addr=0.0.0.0:9091 --datadir=/home/erigon/.local/share/erigon
    ports: [ "30308:30303/tcp", "30308:30303/udp" ]
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"


  rpcdaemon:
    networks:
        erigon:
          ipv4_address: 172.102.1.13
    <<: *default-erigon-service
    command: |
      rpcdaemon --http.api=eth,erigon,net,debug,trace  --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --ws
      --private.api.addr=erigon:9090 --datadir=/home/erigon/.local/share/erigon
    ports: [ "9546:8545" ]
    restart: unless-stopped
    environment:
      TZ: "Asia/Shanghai"

 
  erigon-beacon-chain:
    container_name: erigon-beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v4.0.1
    restart: always
    depends_on:
      - erigon
    networks:
      erigon:
        ipv4_address: 172.102.1.14
    environment:
      TZ: "Asia/Shanghai"
    deploy:
        resources:
          limits:
            cpus: '8'
            memory: '8gb'
          reservations:
            cpus: '8'
            memory: '8gb'
    ports:
      - 4002:4000
      - 13002:13000/tcp
      - 12002:12000/udp
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/erigon/jwt.hex:/root/jwt.hex
      - ${XDG_DATA_HOME:-~/.local/share}/eth2:/data
    command:
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --jwt-secret=/root/jwt.hex
      - --execution-endpoint=http://erigon:8551
      - --checkpoint-sync-url=https://beaconstate.info 
      - --genesis-beacon-api-url=https://beaconstate.info
      - --accept-terms-of-use
    <<: *logging

```

## Version: v2.43.0
The startup parameters for erigon still use the configuration from docker-compose.yaml from v2.37.0.

after start docker container, erigon fatal exited:
```
not allowed change of --prune flag, last time you used: --prune.t.older=90000 --prune.h.older=15000000 --prune.r.before=11052984 --prune.c.older=15000000
```

I cannot run the `integration` command in a container that has exited; But I think this information should be enough to find out a little problem.

thank you~
