### ISSUE TITLE
Syncing of matic mainnet is stucked

### ISSUE THREAD

**Issue by samarthk-systango** [ledgerwatch/erigon#7538]
Hi Team,

I have started the matic node using docker compose but syncing is stucked from last 5 days on one of the block id, we restarted the service multiple times but it's not showing any progress.  

**Current Block	     Latest Block	                 Lag
     41775619	               42843218                    1067599**

**Here are the configuration and services which we have in our docker-compose file**

```
services:
  heimdall:
    image: 0xpolygon/heimdall:0.3.0
    entrypoint: /usr/bin/heimdalld
    command: start --home=/heimdall-home --chain=bor-mainnet
    ports: [ "26657:26657", "26656:26656"]
    volumes:
      - /data/heimdalld:/heimdall-home:rw
    networks:
      - polygon
    restart: unless-stopped

  heimdallr:
    image: 0xpolygon/heimdall:0.3.0
    entrypoint: /usr/bin/heimdalld
    command: rest-server --laddr=tcp://0.0.0.0:1317 --home=/heimdall-home --chain=bor-mainnet --node=tcp://heimdall:26657
    ports: [ "1317:1317"]
    volumes:
      - /data/heimdalld:/heimdall-home:rw
    networks:
      - polygon
    restart: unless-stopped
    depends_on:
      - heimdall

  erigon:
    image: thorax/erigon:v2.42.0
    # build:
    #   args:
    #     UID: ${DOCKER_UID:-1000}
    #     GID: ${DOCKER_GID:-1000}
    #   context: .
    user: root
    command: |
      ${ERIGON_FLAGS-} --private.api.addr=0.0.0.0:9090
      --sentry.api.addr=sentry:9091 --downloader.api.addr=downloader:9093 --txpool.disable
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061 --snapshots=false
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex --datadir=/home/erigon/.local/share/erigon --bor.heimdall=http://heimdallr:1317 --chain=bor-mainnet
    ports: [ "8551:8551" ]
    volumes:
      # It's ok to mount sub-dirs of "datadir" to different drives
      - /data/erigon:/home/erigon/.local/share/erigon
    restart: unless-stopped
    mem_swappiness: 0
    networks:
      - polygon

  sentry:
    <<: *default-erigon-service
    entrypoint: sentry
    command: ${SENTRY_FLAGS-} --sentry.api.addr=0.0.0.0:9091 --datadir=/home/erigon/.local/share/erigon
    ports: [ "30303:30303/tcp", "30303:30303/udp" ]
    networks:
      - polygon

  downloader:
    <<: *default-erigon-service
    entrypoint: downloader 
    command: ${DOWNLOADER_FLAGS-} --downloader.api.addr=0.0.0.0:9093 --datadir=/home/erigon/.local/share/erigon
    ports: [ "42069:42069/tcp", "42069:42069/udp" ]
    networks:
      - polygon

  txpool:
    <<: *default-erigon-service
    entrypoint: txpool
    command: ${TXPOOL_FLAGS-} --private.api.addr=erigon:9090 --txpool.api.addr=0.0.0.0:9094 --sentry.api.addr=sentry:9091 --datadir=/home/erigon/.local/share/erigon
    networks:
      - polygon

  rpcdaemon:
    <<: *default-erigon-service
    entrypoint: rpcdaemon
    command: |
      ${RPCDAEMON_FLAGS-} --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --ws
      --private.api.addr=erigon:9090 --txpool.api.addr=txpool:9094 --datadir=/home/erigon/.local/share/erigon
    ports: [ "8545:8545" ]
    networks:
      - polygon
```

**Here are the hardware details for more information:**

Machine SKU: Standard L16as v3 
vCPU: 16
RAM: 128GB
Disk attached: 16 TB

**Below are the current log snippet of the node :+1:** 

![Screenshot from 2023-05-18 21-17-39](https://github.com/ledgerwatch/erigon/assets/128302698/0f4f9fd5-2e4e-4733-b794-93e7f4528cf6)

![Screenshot from 2023-05-18 21-18-03](https://github.com/ledgerwatch/erigon/assets/128302698/560d60ac-f761-4042-99cc-5e48086b189c)
