### ISSUE TITLE
Engine API is not responding to the Docker Host:  "Recv failure: Connection reset by peer"

### ISSUE THREAD

**Issue by victorelec14** [ledgerwatch/erigon#7566]
#### System information

Erigon version: `./erigon --version`

erigon version 2.43.0-stable-1106475e

OS & Version:  Linux  (Docker version 20.10.21, build baeda1f)

Commit hash:  1106475e

Erigon Command (with flags/config):  

Docker 
```yml
version: "3"
services:
  erigon:
    image: thorax/erigon:v2.43.0
    restart: unless-stopped
    stop_grace_period: 1m
    command:
      - erigon
      - --chain=mainnet
      #- --datadir=/erigon
      - --http
      - --http.api=eth,net,web3,engine,admin,erigon,debug,trace,txpool
      - --private.api.addr=0.0.0.0:9090
      - --authrpc.jwtsecret=/jwt.hex
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts='*'
      #- --snapshots
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts="*"
      - --http.corsdomain="*"
      - --ws
      - --externalcl
      - --nat=any
    user: 'root' #1000:1000
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "30304:30304/tcp"
      - "30304:30304/udp"
      - "42068:42068/tcp"
      - "42068:42068/udp"
      - "8545:8545"
      - "8551:8551"
      - "6060:6060"
    volumes:
      - ./erigon:/root/.local/share/erigon
      - ./jwt.hex:/jwt.hex

```
Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network:  Mainnet

#### Expected behaviour

Erigon does not respond to requests from the Docker host when the Engine API is called on port 8551, it responds with
>  Recv failure: Connection reset by peer

When should I reply "Missing Token"  (normal value when the hex token is not passed in the query)

This only happens from the Docker Host and not inside the container, there if it responds correctly:
```
root@erigon:~# docker exec -it b53618c520ee sh

/ # curl -X POST http://localhost:8551/  -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
missing token
```

#### Actual behaviour

```
root@erigon:~# curl -X POST http://127.0.0.1:8551/  -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
curl: (56) Recv failure: Connection reset by peer
```

#### Steps to reproduce the behaviour
docker-compose up -d
docker exec -it erigon sh
curl -X POST http://localhost:8551/  -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'

#### Backtrace

127.0.0.1 even when the parameter "- --authrpc.addr=0.0.0.0" is set

> erigon_1  | [INFO] [05-23|17:03:45.874] HTTP endpoint opened for Engine API      url=127.0.0.1:8551 ws=true ws.compression=true

````
[backtrace]
````
