### ISSUE TITLE
Caplin stuck at Waiting For Peers after Block 18299999 

### ISSUE THREAD

**Issue by AndrewMohawk** [ledgerwatch/erigon#9046]
Hi,

I am building up my erigorn archive node and noticed that I didnt have the --internalcl flag when I got to block height 18299999. I stopped my docker container, and rebuilt it and I see caplin starting but is simply looping at

`app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s`

It feels like this could have been a port forwarding or `devel` issue, but I get the same on `v2.55.1` , I'm forwarding the following ports into the docker image from the Internet on both TCP and UDP:

```
42069,30303,30304,4000,4001,5555,9093,9000,9100
```

(Some extra as I was trying to debug)

Is there a port I am missing or something else I should be doing to stop this from being stuck at "Waiting For Peers" ?

**Comment by Giulio2002** [comment]
This usually happens when ports are not exposed to the internet, are they all exposed? check the discovery ports

**Comment by AndrewMohawk** [comment]
I have all of those enabled and confirmed that I can connect to them apart from 9000 and 9001, but I actually cant remember what I needed those for. can you confirm which ports are needed for discovery?

**Comment by whidrasl** [comment]
Stuck at the same block. Getting logs like this for several (20) hours already:
`[INFO] [12-31|07:07:36.354] Downloading History                      app=caplin stage=DownloadHistoricalBlocks slot=7671074 blockNumber=18480172 blk/sec=0.0 mbps/sec=0.0000 peers=280 snapshots=0 reconnected=false
[INFO] [12-31|07:07:36.076] [txpool] stat                            pending=0 baseFee=0 queued=30000 alloc=14.3GB sys=31.3GB
[INFO] [12-31|07:07:36.068] [p2p] GoodPeers                          eth68=100 eth67=92 eth66=8
[INFO] [12-31|07:07:06.354] Downloading History                      app=caplin stage=DownloadHistoricalBlocks slot=7671074 blockNumber=18480172 blk/sec=0.0 mbps/sec=0.0000 peers=277 snapshots=0 reconnected=false
[INFO] [12-31|07:07:05.540] P2P                                      app=caplin peers=277
[INFO] [12-31|07:06:36.354] Downloading History                      app=caplin stage=DownloadHistoricalBlocks slot=7671074 blockNumber=18480172 blk/sec=1.1 mbps/sec=0.1629 peers=277 snapshots=0 reconnected=false
[INFO] [12-31|07:06:06.355] Downloading History                      app=caplin stage=DownloadHistoricalBlocks slot=7671106 blockNumber=18480204 blk/sec=0.0 mbps/sec=0.0000 peers=278 snapshots=0 reconnected=false
[INFO] [12-31|07:06:05.540] P2P                                      app=caplin peers=278
[INFO] [12-31|07:05:36.354] Downloading History                      app=caplin stage=DownloadHistoricalBlocks slot=7671106 blockNumber=18480204 blk/sec=1.1 mbps/sec=0.1520 peers=280 snapshots=0 reconnected=false
[INFO] [12-31|07:05:06.354] Downloading History                      app=caplin stage=DownloadHistoricalBlocks slot=7671138 blockNumber=18480236 blk/sec=0.0 mbps/sec=0.0000 peers=281 snapshots=0 reconnected=false
[INFO] [12-31|07:05:05.540] P2P                                      app=caplin peers=281`

Syncing from 0 block, erigon v2.55.1, lightclient.discovery.port and lightclient.discovery.tcpport has the same value and externally available.

**Comment by Giulio2002** [comment]
oh, this is fixed on latest version, some caplin snapshots prototype spilled

**Comment by AndrewMohawk** [comment]
Which ports are needed? I still cant find any peers:

```
2024-01-01 10:12:08 downloader-1  | [INFO] [01-01|15:12:08.075] [snapshots] Seeding                      up=0B/s peers=4 conns=4 files=197 alloc=392.7MB sys=474.9MB
2024-01-01 10:12:10 erigon-1      | [INFO] [01-01|15:12:10.433] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:13 erigon-1      | [INFO] [01-01|15:12:13.434] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:16 erigon-1      | [INFO] [01-01|15:12:16.435] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:19 erigon-1      | [INFO] [01-01|15:12:19.435] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:22 erigon-1      | [INFO] [01-01|15:12:22.436] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:25 erigon-1      | [INFO] [01-01|15:12:25.437] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:28 downloader-1  | [INFO] [01-01|15:12:28.075] [snapshots] Seeding                      up=0B/s peers=2 conns=2 files=197 alloc=240.8MB sys=512.3MB
2024-01-01 10:12:28 erigon-1      | [INFO] [01-01|15:12:28.437] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:31 erigon-1      | [INFO] [01-01|15:12:31.438] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:34 erigon-1      | [INFO] [01-01|15:12:34.439] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:37 erigon-1      | [INFO] [01-01|15:12:37.439] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:40 erigon-1      | [INFO] [01-01|15:12:40.440] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:43 erigon-1      | [INFO] [01-01|15:12:43.440] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
2024-01-01 10:12:46 erigon-1      | [INFO] [01-01|15:12:46.441] [Caplin] Waiting For Peers               app=caplin stage=WaitForPeers have=0 needed=4 retryIn=3s
```

**Comment by zxzyy10** [comment]
> oh, this is fixed on latest version, some caplin snapshots prototype spilled

which version should I choose to solve this problem?

**Comment by AndrewMohawk** [comment]
For anyone who does come to this in the future (and once I have everything configured I will likely make a PR for the docker-compose), there are a few ports missing/incorrect in the compose file, currently what I am using on a windows machine with an attached NVME PCI gen 4 drive (that will move to a server after syncing) :

This seems to work with both `v2.55.1` and `devel` env set. DO NOT leave this unset or it will default to `latest` which is very old.

```
# Erigon by default is "all in one binary" solution, but it's possible start TxPool as separated processes.
# Same true about: JSON RPC layer (RPCDaemon), p2p layer (Sentry), history download layer (Downloader), consensus.
# Don't start services as separated processes unless you have clear reason for it: resource limiting, scale, replace by your own implementation, security.
# This file is an example: how to start Erigon's services as separated processes.

# Default: --datadir=E:/erigon-data
# Default UID: 1000
# Default GID: 1000
# Ports: `9090` execution engine (private api), `9091` sentry, `9092` consensus engine, `9093` snapshot downloader, `9094` TxPool
# Ports: `8545` json rpc, `8551` consensus json rpc, `30303` eth p2p protocol, `42069` bittorrent protocol,

# Connections: erigon -> (sentries, downloader), rpcdaemon -> (erigon, txpool), txpool -> erigon
version: '2.2'

# Basic erigon's service
x-erigon-service: &default-erigon-service
  image: thorax/erigon:${TAG:-latest}
  pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
  volumes_from: [ erigon ]
  restart: unless-stopped
  mem_swappiness: 0
  user: 1000:1000
services:
  erigon:
    image: thorax/erigon:${TAG:-latest}
    build:
      args:
        UID: 1000
        GID: 1000
      context: .
    command: |
      --private.api.addr=0.0.0.0:9090 --internalcl
      --sentry.api.addr=sentry:9091 --downloader.api.addr=downloader:9093 --txpool.disable
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
      --nat "extip:<my_external_ip>"
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex --datadir=/home/erigon/.local/share/erigon
      --http.api "eth,erigon,ots,web3,net,debug,trace,txpool"
      --verbosity 4
      --snap.stop
    ports: [ "4000:4000/udp", "6060:6060","6061:6061","9090:9090","7777:7777","4001:4001","8551:8551","40517:40517"]  

    volumes:
      # It's ok to mount sub-dirs of "datadir" to different drives
      - "E:/erigon-data:/home/erigon/.local/share/erigon"
    restart: unless-stopped
    mem_swappiness: 0
    user: 1000:1000

  sentry:
    <<: *default-erigon-service
    entrypoint: sentry
    command: --sentry.api.addr=0.0.0.0:9091 --datadir=/home/erigon/.local/share/erigon
    ports: [ "30303:30303/tcp", "30303:30303/udp","30304:30304/tcp", "30304:30304/udp", "9091:9091" ]

  downloader:
    <<: *default-erigon-service
    entrypoint: downloader 
    command: --downloader.api.addr=0.0.0.0:9093 --datadir=/home/erigon/.local/share/erigon --torrent.download.rate=5000mb --torrent.maxpeers 300 --verbosity 4 --torrent.verbosity=4 --torrent.port 42069
    ports: [ "42069:42069/tcp", "42069:42069/udp", "9093:9093"  ]
    

  txpool:
    <<: *default-erigon-service
    entrypoint: txpool
    command: --private.api.addr=erigon:9090 --txpool.api.addr=0.0.0.0:9094 --sentry.api.addr=sentry:9091 --datadir=/home/erigon/.local/share/erigon
    ports: [ "9094:9094"  ]

  rpcdaemon:
    <<: *default-erigon-service
    entrypoint: rpcdaemon
    command: |
      --http.addr=0.0.0.0 --http.vhosts=any --http.corsdomain=* --ws
      --private.api.addr=erigon:9090 --txpool.api.addr=txpool:9094 --datadir=/home/erigon/.local/share/erigon
    ports: [ "8545:8545" ]




  prometheus:
    image: prom/prometheus:v2.47.2
    user: 1000:1000 # Uses erigon user from Dockerfile
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=150d --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    
    volumes:
      - "E:/erigon-data/cmd/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "E:/erigon-data/erigon-prometheus:/prometheus"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.1
    user: "472:0" # required for grafana version >= 7.3
    ports: [ "3000:3000" ]
    volumes:
      - "E:/erigon-data/cmd/prometheus/grafana.ini:/etc/grafana/grafana.ini"
      - "E:/erigon-data/cmd/prometheus/datasources:/etc/grafana/provisioning/datasources"
      - "E:/erigon-data/cmd/prometheus/dashboards:/etc/grafana/provisioning/dashboards"
      - "E:/erigon-data/erigon-grafana:/var/lib/grafana"
    restart: unless-stopped
```

I went into each container and did `netstat -natp | grep -i listen` to see what was listening and then forwarded those ports. `40517` is likely not needed, but leaving it in since its finally moving! But this strategy should work for you as well
